[workspace]
members = [
    "snake-pyo3",
]
resolver = "2"

[workspace.dependencies]
futures = "0.3"
par-stream = { version = "0.10.2", features = ["runtime-tokio"] }
tokio = { version = "1", features = ["full"] }
async-stream = "0.3.5"
